name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ENVIRONMENT SETUP
    - name: Setup Docker
      uses: docker/setup-action@v2

    # LINTING STAGE
    - name: Run Linting Scripts
      run: |
        docker-compose -f docker-compose.yml run linting
      # QUALITY GATE: Fails on linting errors

    # BUILD STAGE
    - name: Build Docker Image
      run: |
        docker build -t myapp .
      # QUALITY GATE: Fails on build errors

    # TEST STAGE
    - name: Run Validation Checks
      run: |
        docker-compose -f docker-compose.yml run validation
      # QUALITY GATE: Fails on test failures