name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # LINTING STAGE
    - name: Configure ESLint
      run: |
        npm install eslint --save-dev
        npx eslint --init
      # COMMENT: Auto-configured since no linter present

    - name: Run Linter
      run: npx eslint .
      # QUALITY GATE: Fails on style violations

    # ARTIFACTS
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: web-files
        path: |
          /tmp/repo_560941879_e136fc2d/README.md
          /tmp/repo_560941879_e136fc2d/index.html
          /tmp/repo_560941879_e136fc2d/scripts/script.js
          /tmp/repo_560941879_e136fc2d/styles/style.css
